apiVersion: 1
groups:
    - orgId: 1
      name: AlertLatency
      folder: AlertFolder
      interval: 1m
      rules:
        - uid: cetd02ppyydq8f
          title: Latency (Response Time) 0,99 Квантиль
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: prometheus
                editorMode: code
                expr: histogram_quantile(0.99, sum by(le, method, route, code) (rate(http_request_duration_seconds_bucket{route=~"/api/.*"}[5m])))
                instant: true
                interval: ""
                intervalMs: 30000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: 35eff187-f045-4273-aa1b-8586d44ba8b6
          panelId: 3
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: 35eff187-f045-4273-aa1b-8586d44ba8b6
            __panelId__: "3"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
