# Общие настройки
app:
  name: "homework-service"
  replicaCount: 2
  image:
    repository: "mxbooll/homework_2m_9l"
    tag: "latest"
    pullPolicy: "Always"

# Конфигурация приложения
config:
  loggingLevel: "Information"
  aspnetCoreLevel: "Warning"
  allowedHosts: "*"

# Настройки БД (без пароля)
postgres:
  host: "postgres-service"
  port: "5432"
  db: "projectotus"
  user: "postgres"  

# Настройки Ingress
ingress:
  enabled: true
  className: "nginx"
  host: "arch.homework"
  path: "/health"
  pathType: "Exact"