{
 "title": "Otus. Split api methods",
 "description": "Метрики с разбивкой по API методам",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency (Response Time) 0,5 Квантиль",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method, route, code) (rate(http_request_duration_seconds_bucket{route=~\"/api/.*\"}[5m])))",
     "legendFormat": "{{0,5 Квантиль}}"
    }
   ]
  },
  {
   "title": "Latency (Response Time) 0,95 Квантиль",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, route, code) (rate(http_request_duration_seconds_bucket{route=~\"/api/a|/api/b\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (Response Time) 0,99 Квантиль",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, method, route, code) (rate(http_request_duration_seconds_bucket{route=~\"/api/.*\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate 5xx",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(custom_request_duration_seconds_count{code=~\"5..\"}[1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}