{
 "title": "Otus.  Nginx-ingress-controller",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "0,5 Квантиль",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le, ingress))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0,95 Квантиль",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le, ingress))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0,99 Квантиль",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le, ingress))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(nginx_ingress_controller_requests[1m])\r\n) by (ingress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate 5xx",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5..\"}[1m])) by (ingress)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}