apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homework-otus-chart.fullname" . }}-postgres
  labels:
    {{- include "homework-otus-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-host: {{ .Values.postgres.host | quote }}
  postgres-port: {{ .Values.postgres.port | quote }}
  postgres-db: {{ .Values.postgres.db | quote }}
  postgres-user: {{ .Values.postgres.user | quote }}
  postgres-password: {{ .Values.postgres.password | default "" | quote }}