apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    {{- include "homework-otus-chart.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
  clusterIP: None