apiVersion: v1
kind: Service
metadata:
  name: {{ include "homework-otus-chart.fullname" . }}
  namespace: default # можно разместить в разнем namespaces (prod, test, etc)
  labels:
    {{- include "homework-otus-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "homework-otus-chart.name" . }}
  ports:
    - port: 80
      targetPort: 80  
      protocol: TCP
      name: web
    - port: 9093
      targetPort: 80
      protocol: TCP
      name: metrics