apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homework-otus-chart.fullname" . }}-config
  labels:
    {{- include "homework-otus-chart.labels" . | nindent 4 }}
data:
  Logging__LogLevel__Default: {{ .Values.config.loggingLevel | quote }}
  Logging__LogLevel__Microsoft.AspNetCore: {{ .Values.config.aspnetCoreLevel | quote }}
  AllowedHosts: {{ .Values.config.allowedHosts | quote }}