apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homework-otus-chart.fullname" . }}
  labels:
    {{- include "homework-otus-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "homework-otus-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homework-otus-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ include "homework-otus-chart.fullname" . }}-config
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: {{ include "homework-otus-chart.fullname" . }}-postgres
              key: postgres-host
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "homework-otus-chart.fullname" . }}-postgres
              key: postgres-port
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ include "homework-otus-chart.fullname" . }}-postgres
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "homework-otus-chart.fullname" . }}-postgres
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "homework-otus-chart.fullname" . }}-postgres
              key: postgres-password
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10