apiVersion: v1
kind: Service
metadata:
  name: {{ include "homework-otus-chart.fullname" . }}
  labels:
    {{- include "homework-otus-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "homework-otus-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80